stages:
  - build
  - check

Сборка:
  stage: build
  script:
    - gradle assemble

Проверка стиля кодирования:
  stage: check
  script:
    - gradle checkstyleMain
    - gradle checkstyleTest
  artifacts:
    when: always
    paths:
      - build/reports/checkstyle/*.html

Тестирование:
  stage: check
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
